addpath('C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Toolkits\Controls\GCoSim\Simulink');
%addpath('C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Toolkits\Controls\Matlab');
RecurDyn='C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Bin\';
RecurDyn_CoSim='C:\Program Files\FunctionBay, Inc\RecurDyn V9R5\Toolkits\Controls\GCoSim\Simulink';
RecurDyn_model='cart_pole';
r_temp___=size(RecurDyn_model);
RecurDyn_model_n=r_temp___(2);
Output_File='cart_pole_GCoSim1';
r_temp___=size(Output_File);
Output_file_n =r_temp___(2);
GCoSim_Name='GCoSim1';
r_temp___ = size(GCoSim_Name);
GCoSim_Name_n = r_temp___(2);
if(exist([RecurDyn_model,'.rdyn']))
  RecurDyn_inputs = 'CartForce';
  RecurDyn_outputs = 'x!x_dot!q!q_dot';
  RecurDyn_io_ids = [  1  2  3  4  5 ];
  RecurDyn_controltimestep = 1.e-003;
  Plant_inputs = Rearrange_io( RecurDyn_inputs );
  Plant_outputs = Rearrange_io( RecurDyn_outputs );
  r_temp___=size(Plant_inputs);
  Plant_inputs_num=r_temp___(1);
  r_temp___=size(Plant_outputs);
  Plant_outputs_num=r_temp___(1);
  r_temp___=version;
  Matlab_version=str2double(r_temp___(1));
  disp('');
  disp('===== RecurDyn & Matlab/SIMULINK ==========');
  disp('%%% INFO : RecurDyn plant actuators names :');
  disp([int2str([1:size(Plant_inputs,1)]'),blanks(size(Plant_inputs,1))',Plant_inputs]);
  disp('%%% INFO : RecurDyn plant sensors names :');
  disp([int2str([1:size(Plant_outputs,1)]'),blanks(size(Plant_outputs,1))',Plant_outputs]);
  disp( '=============================================' ) ;
% disp( '************************ Reserved Variables ************************* ' ) ;
% disp( '* Plant_inputs,Plant_outputs,RecurDyn,RecurDyn_model,RecurDyn_static*' ) ;
% disp( '* RecurDyn_inputs,RecurDyn_io_ids,RecurDyn_outputs                  *' ) ;
% disp( '* RecurDyn_controltimestep,RecurDyn_show,RecurDyn_step              *');
% disp( '************* Reserved variables can not be changed ***************** ' ) ;
  disp( ' ' ) ;
else
  disp('');
  disp('%%% ERROR : missing RecurDyn plant model file !!!');
  disp('');
end
  clear r_temp___;
